services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: secondbrain-dev
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/secondbrain
      - ENVIRONMENT=development
      - VAULT_STORAGE_PATH=/workspace/storage/vaults
