services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: secondbrain-dev
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/secondbrain
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
